/**
 ******************************************************************************
 *
 *  The MIT License
 *  Copyright (c) 2016 MXCHIP Inc.
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to deal
 *  in the Software without restriction, including without limitation the rights
 *  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *  copies of the Software, and to permit persons to whom the Software is furnished
 *  to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included in
 *  all copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 *  WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR
 *  IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 ******************************************************************************
 */


const char * page_head = "<!doctype html>"
"<html><head>"
"<meta http-equiv=\"content-type\" content=\"text/html\" charset=\"utf-8\">"
"<meta content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0\" name=\"viewport\">"
"<title>AZ3166 WIFI Config</title>"
"<style>"
"body, p, h1, h2, h3, h4, h5, h6, ul, ol, li, dl, dt, dd, table, th, td, form, fieldset, legend, input, textarea, button, select, img, blockquote{"
"	margin: 0;"
"	padding: 0;"
"	border: 0;"
"	font-size: 100%;"
"	vertical-align: baseline;"
"	font-family: \"Microsoft YaHei\",\"iconfont\",\"FontAwesome\"  !important;"
"}"
"h1, h2, h3, h4, h5, h6 {font-weight: normal;}"
"body{background: #f5f5f5 }"
"body, html{"
"	height: 100%;"
"	max-height: 100%;"
"}"
"html{font-size:62.5%;}"
".main{"
"	width:100%;"
"	min-height:100%;"
"	position:relative;"
"	box-sizing: border-box;"
"	-webkit-box-sizing:border-box;"
"	display:-webkit-box;"
"	-webkit-box-orient:vertical;"
"}"
".header{"
"	background: #0078d7;"
"	height:48px;"
"	line-height:48px;"
"	overflow: hidden;"
"	width: 100%;"
"	box-sizing: border-box;"
"	position: relative;"
"}"
".header h3{"
"	font-size: 18px;"
"	line-height: 48px;"
"	text-align: center;"
"	color: #fff;"
"}"
".wifi-set .content{"
"	margin:10px;"
"	-webkit-box-flex: 1;"
"	-moz-box-flex: 1;"
"	-webkit-flex: 1;"
"	-ms-flex: 1;"
"	flex: 1;"
"}"
".gateway-info-box .input-field{"
"	line-height:20px;"
"	vertical-align:middle;"
"	border: 1px solid #d7d7d7;"
"	height: 58px;"
"	background: #fff;"
"	box-sizing: border-box;"
"	position: relative;"
"	padding: 19px 15px 19px 18px;"
"	max-width: 500px;"
"	margin: auto;"
"}"
".input-field input{"
"	height: 20px;"
"	line-height: 20px;"
"	font-size: 14px;"
"	width: 100%;"
"	border: 0 none;"
"	background: transparent;"
"	outline: medium;"
"}"
".input-field:first-of-type{"
"	border-top-left-radius: 5px;"
"	border-top-right-radius: 5px;"
"}"
".input-field:last-of-type{"
"	border-bottom-left-radius: 5px;"
"	border-bottom-right-radius: 5px;"
"}"
".btn{"
"	height:40px;"
"	line-height:40px;"
"	font-size:14px;"
"	display:block;"
"	border: 0 none;"
"	color: #FFF;"
"	background-color:#0078d7;"
"	border-radius: 5px;"
"	-moz-border-radius: 5px;"
"	-webkit-border-radius: 5px;"
"	outline: none;"
"	cursor: pointer;"
"	text-align:center;"
"	min-width:70px;"
"	padding:0 10px;"
"}"
".gateway-btn button{"
"	width: 100%;"
"	max-width: 100px;"
"	margin:35px auto;"
"}"
".input-field.file-selector{"
"	padding-top: 0px !important;"
"	padding-bottom: 0px !important;"
"	padding-right: 0px !important;"
"}"
".inputfile{"
"	width: 0.1px;"
"	height: 0.1px;"
"	opacity: 0;"
"	overflow: hidden;"
"	position: absolute;"
"	z-index: -1;"
"}"
".inputfile + label{"
"	width: 100%;"
"	font-size: 14px;"
"	line-height: 4;"
"}"
".inputfile + label span{"
"	max-width: calc(100% - 120px);"
"	float: left;"
"	text-overflow: ellipsis;"
"	white-space: nowrap;"
"	overflow: hidden;"
"}"
".inputfile + label p{"
"	min-width: 120px;"
"	text-align: center;"
"	background-color: #0078d7;"
"	color: #FFF;"
"	float: right;"
"}"
".wifi-result .content{"
"	-webkit-box-flex: 1;"
"	-moz-box-flex: 1;"
"	-webkit-flex: 1;"
"	-ms-flex: 1;"
"	flex: 1; "
"	padding:10px;"
"	background-color:#FFF;"
"}"
".wifi-result h2{"
"	font-size:24px;"
"	text-align:center;"
"	padding:30px 0;"
"	line-height:30px;"
"}"
".wifi-result p{"
"	text-indent:2rem;"
"	font-size:16px;"
"	line-height:28px;"
"}"
"</style></head>";


/* Split WiFi setting body to two parts, just to save dynamic memory use during request handling. 
 * Will refactor this after the demo.
 */
const char *wifi_setting_a = "<body><div class=\"main wifi-set\">"
"<header class=\"header\"><h3>AZ3166 WIFI Config</h3></header>"
"<div class=\"content\"><form action=\"result\" method=\"post\" enctype=\"multipart/form-data\">"
" <section class=\"gateway-info-box\">"
"  <div class=\"input-field\">"
"   <input id=\"ssid\" type=\"text\" name=\"SSID\" value=\"";

const char *wifi_setting_b = "\" placeholder=\"SSID\">"
"  </div>"
"  <div class=\"input-field\">"
"  <input type=\"password\" name=\"PASS\" value=\"\" placeholder=\"Password. Leave blank if password is not required.\">"
"  </div>"
" </section>"
" <section class=\"gateway-btn\"><button type=\"submit\" name=\"next\" class=\"btn\">SAVE</button></section>"
" </form></div></div></body></html>";

const char *success_result = "<body><div class=\"main wifi-result\">"
" <header class=\"header\"><h3>AZ3166 WIFI Config</h3></header>"
" <div class=\"content\"><h2 style=\"color: #0078d7;\">Saved Successfully</h2></div>"
"</div></body></html>";

const char *failed_result = "<body><div class=\"main wifi-result\">"
" <header class=\"header\"><h3>AZ3166 WIFI Config</h3></header>"
" <div class=\"content\"><h2 style=\"color: red;\">Save Failed</h2></div>"
"</div></body></html>";
